export const horseNames = [
  'Ada Lovelace',
  'Grace Hopper',
  'Margaret Hamilton',
  'Joan Clarke',
  'Alan Turing',
  'Edsger Dijkstra',
  'Donald Knuth',
  'Barbara Liskov',
  'Linus Torvalds',
  'Ken Thompson',
  'Dennis Ritchie',
  'Tim Berners-Lee',
  'James Gosling',
  'Guido van Rossum',
  'Brendan Eich',
  'Bjarne Stroustrup',
  'John McCarthy',
  'Niklaus Wirth',
  'Sophie Wilson',
  'Radia Perlman',
];
