name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Prettier check
        run: yarn format:check

      - name: ESLint
        run: yarn lint:ci
